import { test, expect } from '@playwright/test';

const RESUME_LIKE_PDF_BASE64 = 'JVBERi0xLjQKJeLjz9MKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MDAgODAwXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA0IDAgUiA+PiA+PiAvQ29udGVudHMgNSAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iago1IDAgb2JqCjw8IC9MZW5ndGggOTY1ID4+CnN0cmVhbQpCVAovRjEgMjIgVGYKNzIgNzMwIFRkCihBUlVOS1VNQVIgSykgVGoKL0YxIDEwIFRmCjAgLTIyIFRkCihTZW5pb3IgU29mdHdhcmUgRW5naW5lZXIgfCBKYXZhIHwgU3ByaW5nIEJvb3QgfCBNaWNyb3NlcnZpY2VzKSBUagovRjEgMTMgVGYKMCAtMzggVGQKKFBST0ZFU1NJT05BTCBTVU1NQVJZKSBUagovRjEgMTAgVGYKMCAtMjAgVGQKKDcrIHllYXJzIG9mIGV4cGVyaWVuY2UgZGVzaWduaW5nIGFuZCBzY2FsaW5nIGVudGVycHJpc2UpIFRqCjAgLTE0IFRkCihiYWNrZW5kIHN5c3RlbXMgaW4gbG9naXN0aWNzIGFuZCBoZWFsdGhjYXJlLikgVGoKMCAtMTQgVGQKKFByb2ZpY2llbnQgaW4gSmF2YSA4LCBTcHJpbmcgQm9vdCwgbWljcm9zZXJ2aWNlcywgYW5kIE9yYWNsZSBEQi4pIFRqCi9GMSAxMyBUZgowIC0zNCBUZAooUFJPRkVTU0lPTkFMIEVYUEVSSUVOQ0UpIFRqCi9GMSAxMSBUZgowIC0yMCBUZAooU2VuaW9yIFByb2R1Y3QgRW5naW5lZXIpIFRqCi9GMSA5IFRmCjAgLTE1IFRkCihEZXNpZ25lZCBtb2R1bGFyIFdNUyBzZXJ2aWNlcyBpbiBKYXZhIGFuZCBTcHJpbmcgQm9vdCwpIFRqCjAgLTEzIFRkCihpbnRlZ3JhdGluZyBvcmRlciwgaW52ZW50b3J5LCBhbmQgZnVsZmlsbG1lbnQgd29ya2Zsb3dzLikgVGoKMCAtMTMgVGQKKEltcHJvdmVkIFJFU1QgQVBJIHRocm91Z2hwdXQgdGhyb3VnaCByZXNwb25zZSBjYWNoaW5nLikgVGoKL0YxIDEyIFRmCjMwMCA5NiBUZAooVEVDSE5JQ0FMIFNLSUxMUykgVGoKL0YxIDkgVGYKMCAtMjAgVGQKKEphdmEgOCwgSmF2YVNjcmlwdCBFUzYrLCBQTC9TUUwsIFNRTCkgVGoKMCAtMTQgVGRCihTcHJpbmcgQm9vdCwgU3ByaW5nIE1WQywgU3ByaW5nIFNlY3VyaXR5KSBUagowIC0xNCBUZAooTWljcm9zZXJ2aWNlcywgUkVTVCBBUElzLCBTcHJpbmcgQmF0Y2gpIFRqCjAgLTE0IFRkCihSZWFjdCwgRnVuY3Rpb25hbCBDb21wb25lbnRzLCBIb29rcykgVGoKRVQKZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwMDA2NCAwMDAwMCBuIAowMDAwMDAwMTIxIDAwMDAwIG4gCjAwMDAwMDAyNDcgMDAwMDAgbiAKMDAwMDAwMDMxNyAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDYgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjEzMzMKJSVFT0YK';

function resumeLikePdfBuffer() { return Buffer.from(RESUME_LIKE_PDF_BASE64, 'base64'); }
async function openPdf(page: import('@playwright/test').Page, buffer: Buffer, name = 'resume-like.pdf') { const chooserPromise = page.waitForEvent('filechooser'); await page.getByRole('button', { name: 'Open' }).click(); const chooser = await chooserPromise; await chooser.setFiles({ name, mimeType: 'application/pdf', buffer }); }
async function enterEditMode(page: import('@playwright/test').Page) { await page.getByRole('button', { name: 'Edit Text' }).click(); const textLayer = page.locator('[aria-label="PDF text layer"]'); await expect(textLayer).toBeVisible({ timeout: 20000 }); await expect(textLayer).toHaveAttribute('data-text-item-count', /[1-9]\d*/, { timeout: 20000 }); await expect(textLayer).toHaveAttribute('data-text-block-count', /[1-9]\d*/, { timeout: 20000 }); return textLayer; }

test('resume-like multi-column PDF uses invisible logical edit targets', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }); });
  await page.goto('/'); await openPdf(page, resumeLikePdfBuffer());
  const textLayer = await enterEditMode(page);
  const itemCount = Number(await textLayer.getAttribute('data-text-item-count')); const blockCount = Number(await textLayer.getAttribute('data-text-block-count'));
  expect(itemCount).toBeGreaterThan(blockCount); expect(await textLayer.locator('[data-pdf-text-block="true"]').count()).toBe(blockCount);
  const styles = await textLayer.locator('[data-pdf-text-block="true"]').evaluateAll((elements) => elements.slice(0, 25).map((element) => { const computed = getComputedStyle(element); return { border: computed.border, outline: computed.outline, background: computed.backgroundColor, boxShadow: computed.boxShadow }; }));
  for (const style of styles) { expect(style.border).toMatch(/0px|transparent/); expect(style.outline).toMatch(/none|0px/); expect(style.background).toMatch(/rgba\(0, 0, 0, 0\)|transparent/); expect(style.boxShadow).toMatch(/none/); }
  const target = textLayer.locator('[data-pdf-text-block="true"]').first(); await target.click(); const editor = page.locator('[contenteditable="true"]').first(); await expect(editor).toBeVisible(); await expect(page.getByRole('toolbar', { name: 'PDF text formatting' })).toBeVisible();
  await editor.fill('Senior Java Developer\nwith 8+ years'); await editor.press('Enter'); await expect(editor).toBeHidden(); await expect(page.getByText('● Unsaved changes')).toBeVisible();
});

test('edited PDF can be downloaded after inline text editing', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }); });
  await page.goto('/'); await openPdf(page, resumeLikePdfBuffer()); const textLayer = await enterEditMode(page); await textLayer.locator('[data-pdf-text-block="true"]').first().click(); const editor = page.locator('[contenteditable="true"]').first(); await editor.fill('PDF Editor Verified'); await editor.press('Enter'); await expect(editor).toBeHidden(); const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download' }).click(); const file = await download; expect(file.suggestedFilename()).toBe('edited.pdf'); expect(await file.path()).toBeTruthy();
});

test('Save PDF uses the same valid PDF pipeline', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }); });
  await page.goto('/'); await expect(page.getByRole('button', { name: 'Save PDF' })).toBeEnabled({ timeout: 20000 }); const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save PDF' }).click(); const file = await download; expect(file.suggestedFilename()).toBe('edited.pdf'); expect(await file.path()).toBeTruthy();
});
